// Interest catalog focused on relationship compatibility, personality, dating style,
// communication, lifestyle and shared activities.
export const CATEGORIES = [
  ['relationship_goals','Relationship Goals','💞'],
  ['love_language','Love Languages','💌'],
  ['personality_vibe','Personality & Vibe','✨'],
  ['dating_style','Dating Style','🌹'],
  ['conversation','Conversation & Connection','💬'],
  ['lifestyle','Lifestyle Compatibility','🌿'],
  ['activities','Fun & Activities','🎉'],
  ['values','Values & Compatibility','🤝'],
  ['romance','Romance & Affection','❤️'],
  ['future','Future & Commitment','💍'],
].map(([id,name,emoji], i) => ({ id, name, emoji, sort_order:i+1 }));

const groups = {
  relationship_goals:[
    ['friendship_first','Friendship First','🫶'],
    ['serious_relationship','Serious Relationship','💖'],
    ['long_term','Long-Term Relationship','💍'],
    ['casual_chat','Casual Chat','💬'],
    ['getting_to_know','Getting To Know Each Other','🌱'],
    ['best_friend','Best Friend Connection','👯'],
    ['soulmate','Soulmate Energy','✨'],
    ['open_to_see','Open To See Where It Goes','🌈'],
  ],
  love_language:[
    ['words_affirmation','Words of Affirmation','💌'],
    ['quality_time','Quality Time','⏰'],
    ['acts_service','Acts of Service','🤲'],
    ['gifts','Thoughtful Gifts','🎁'],
    ['physical_affection','Affection','🤗'],
    ['attention','Consistent Attention','💞'],
    ['reassurance','Reassurance','🫂'],
    ['support','Emotional Support','❤️‍🩹'],
  ],
  personality_vibe:[
    ['introvert','Introvert','🌙'],
    ['extrovert','Extrovert','☀️'],
    ['ambivert','Ambivert','⚖️'],
    ['shy','Shy & Soft','🌸'],
    ['confident','Confident','🔥'],
    ['funny','Funny','😂'],
    ['calm','Calm & Chill','🌿'],
    ['romantic','Romantic','🌹'],
  ],
  dating_style:[
    ['slow_burn','Slow Burn','🐢'],
    ['direct','Direct & Honest','🎯'],
    ['flirty','Playful & Flirty','😉'],
    ['thoughtful','Thoughtful Dates','🌷'],
    ['spontaneous','Spontaneous','⚡'],
    ['traditional','Traditional Romance','💐'],
    ['modern','Modern Dating','📱'],
    ['friends_to_lovers','Friends To Something More','💗'],
  ],
  conversation:[
    ['deep_talks','Deep Talks','🧠'],
    ['late_night_chats','Late-Night Chats','🌙'],
    ['daily_checkins','Daily Check-Ins','📲'],
    ['voice_calls','Voice Calls','📞'],
    ['texting','Texting','💬'],
    ['jokes_memes','Jokes & Memes','🤣'],
    ['storytelling','Storytelling','📖'],
    ['advice','Giving Advice','💡'],
  ],
  lifestyle:[
    ['homebody','Homebody','🏠'],
    ['adventurous','Adventurous','🧗'],
    ['fitness','Fitness','🏋️'],
    ['foodie','Foodie','🍜'],
    ['music','Music','🎵'],
    ['movies','Movies & Series','🎬'],
    ['travel','Travel','✈️'],
    ['gaming','Gaming','🎮'],
  ],
  activities:[
    ['coffee_dates','Coffee Dates','☕'],
    ['movie_dates','Movie Dates','🍿'],
    ['beach','Beach Days','🏖️'],
    ['walks','Walks Together','🚶'],
    ['restaurants','Restaurant Dates','🍽️'],
    ['concerts','Concerts','🎤'],
    ['shopping','Shopping','🛍️'],
    ['photography','Taking Photos','📸'],
  ],
  values:[
    ['honesty','Honesty','🤍'],
    ['loyalty','Loyalty','🔐'],
    ['respect','Respect','🙏'],
    ['trust','Trust','🤝'],
    ['kindness','Kindness','💚'],
    ['communication','Good Communication','🗣️'],
    ['family','Family-Oriented','👨‍👩‍👧'],
    ['ambition','Ambition','🚀'],
  ],
  romance:[
    ['cute_messages','Cute Messages','💌'],
    ['good_morning','Good Morning Texts','🌅'],
    ['good_night','Good Night Texts','🌙'],
    ['surprises','Sweet Surprises','🎁'],
    ['flowers','Flowers','💐'],
    ['date_nights','Date Nights','🌃'],
    ['anniversaries','Special Occasions','🎊'],
    ['affectionate','Affectionate Energy','❤️'],
  ],
  future:[
    ['commitment','Commitment','💍'],
    ['marriage_minded','Marriage-Minded','💒'],
    ['building_together','Building Together','🏡'],
    ['career_support','Supporting Each Other','🤝'],
    ['family_plans','Family Goals','👨‍👩‍👧'],
    ['financial_goals','Financial Goals','📈'],
    ['personal_growth','Growing Together','🌱'],
    ['long_distance','Long-Distance Friendly','🌍'],
  ],
};

export const INTERESTS = Object.entries(groups).flatMap(([category_id, items]) =>
  items.map(([id,name,emoji]) => ({ id, name, emoji, category_id }))
);
